
DBCC CHECKIDENT ('dbo.ExcessTierLog', RESEED, 0);    
INSERT INTO dbo.ExcessTierLog ([CustomerSessionID]
      ,[ChargeRateMoney]
      ,[ChargeValueMoney]
      ,[ChargeCurrency]
      ,[Origin]
      ,[Destination]
      ,[Company]
      ,[Flightnumber]
      ,[IsExcessByWeight]
      ,[NumberOfExcessWeight]
      ,[ExcessByWeightChargeRate]
      ,[ExcessByWeightChargeCurrency]
      ,[IsExcessByPieces]
      ,[NumberOfExcessPieces]
      ,[ExcessByPiecesChargeRate]
      ,[ExcessByPiecesChargeCurrency]
      ,[IsExcessByOtherType]
      ,[NumberOfExcessByOtherType]
      ,[ExcessByOtherTypeChargeRate]
      ,[ExcessByOtherTypeChargeCurrency]
      ,[IsHeavyCharge]
      ,[NumberOfHeavyChargeItems]
      ,[ExcessByHeavyChargeRate]
      ,[ExcessByHeavyChargeCurrency]
      ,[IsOtherHeavyChargeType]
      ,[NumberOfOtherHeavyChargeItems]
      ,[ExcessByOtherHeavyChargeRate]
      ,[ExcessByOtherHeavyChargeCurrency])
SELECT [CustomerSessionID]
      ,[ChargeRateMoney]
      ,[ChargeValueMoney]
      ,[ChargeCurrency]
      ,[Origin]
      ,[Destination]
      ,[Company]
      ,[Flightnumber]
      ,[IsExcessByWeight]
      ,[NumberOfExcessWeight]
      ,[ExcessByWeightChargeRate]
      ,[ExcessByWeightChargeCurrency]
      ,[IsExcessByPieces]
      ,[NumberOfExcessPieces]
      ,[ExcessByPiecesChargeRate]
      ,[ExcessByPiecesChargeCurrency]
      ,[IsExcessByOtherType]
      ,[NumberOfExcessByOtherType]
      ,[ExcessByOtherTypeChargeRate]
      ,[ExcessByOtherTypeChargeCurrency]
      ,[IsHeavyCharge]
      ,[NumberOfHeavyChargeItems]
      ,[ExcessByHeavyChargeRate]
      ,[ExcessByHeavyChargeCurrency]
      ,[IsOtherHeavyChargeType]
      ,[NumberOfOtherHeavyChargeItems]
      ,[ExcessByOtherHeavyChargeRate]
      ,[ExcessByOtherHeavyChargeCurrency]
FROM (DELETE FROM ExcessTierLog OUTPUT deleted.*) d;

