SELECT [ID]
      ,[CustomerID]
      ,[AbdStationID]
      ,[CustomerLookupType]
      ,[PNR]
      ,[UtcCreationTime]
      ,[FlightID]
      ,[TimeSlot5minID]
      ,[TimeSlot10minID]
      ,[TimeSlotHourlyID]
      ,[DayOfTheWeekID]
      ,[LocalTime]
      ,[UtcCompletionTime]
      ,[SessionDuration]
      ,[SessionEndReasonID]
      ,[SessionEndPageID]
      ,[MachineTime]
      ,[PaxTime]
      ,[DcsTime]
      ,[BhsTime]
      ,[CsaTime]
      ,isnull(cast(cast(DATEDIFF(MILLISECOND, [UtcCreationTime], [UtcCompletionTime]) as decimal(12, 2))/1000 as decimal(12,2)), 0.00) as SessionDurationCalculation
  FROM [ReportingDB_NRT].[dbo].[CustomerSession]
  WHERE [SessionDuration] is null
  order by ID desc
