 
declare @tblNoticeTemplate TABLE
(
	[NoticeTemplateID] [smallint] NOT NULL,
	[NoticeTemplateStatusID] [smallint] NOT NULL,
	[TemplateName] [varchar](100) NOT NULL,
	[SystemTemplateFlag] [bit] NOT NULL,
	[SystemTemplateCode] [varchar](5) NULL,
	[ApplicationAppliedFlag] [bit] NOT NULL,
	[ClockRequiredFlag] [bit] NOT NULL,
	[ClockID] [smallint] NULL,
	[LinkToPrimaryRecordFlag] [bit] NOT NULL,
	[InstrumentTypeID] [smallint] NULL,
	[ApplyToDraftRecord] [bit] NOT NULL,
	[ApplyToIssuedRecord] [bit] NOT NULL,
	[LinkToAccountablePartyFlag] [bit] NOT NULL,
	[LinkToContactFlag] [bit] NOT NULL,
	[LinkToLocationFlag] [bit] NOT NULL,
	[DefaultFollowupDays] [smallint] NULL,
	[ExternalNoticeFlag] [bit] NOT NULL,
	[IssuedByDelegatedOfficerFlag] [bit] NOT NULL,
	[DocumentRequiredFlag] [bit] NOT NULL,
	[PublicRegisterFlag] [bit] NOT NULL,
	[AppealableFlag] [bit] NOT NULL,
	[FeeApplicableFlag] [bit] NOT NULL,
	[FeeEditableFlag] [bit] NOT NULL,
	[FeeTypeID] [smallint] NULL,
	[DefaultFeeAmount] [money] NULL,
	[ProgressFlag] [bit] NOT NULL,
	[Progress] [varchar](100) NULL,
	[ProgressStatus] [varchar](50) NULL,
	[FinalStageFlag] [bit] NOT NULL,
	[ProgressClockRequiredFlag] [bit] NOT NULL,
	[ProgressClockID] [smallint] NULL,
	[InpectionDateAppliedFlag] [bit] NULL,
	[TemplateDocument] [varbinary](max) NULL,
	[DateCreated] [smalldatetime] NOT NULL,
	[CreatedBySystemUserID] [int] NOT NULL,
	[DateUpdated] [smalldatetime] NULL,
	[UpdatedBySystemUserID] [int] NULL,
	[RowTimestamp] [timestamp] NOT NULL,
	[FeeSentToSAPWhileIssueFlag] [bit] NOT NULL,
	[AuditTypeID] [smallint] NULL,
	[ExemptionNoticeFlag] [bit] NOT NULL,
	[EnforceableUndertakingFlag] [bit] NOT NULL 
)

delete from @tblNoticeTemplate where NoticeTemplateID in (403, 404, 405, 406, 407)
 
--403
insert into @tblNoticeTemplate
(
	NoticeTemplateID, 
	NoticeTemplateStatusID, 
	TemplateName, 
	SystemTemplateFlag, 
	SystemTemplateCode, 
	LinkToPrimaryRecordFlag, 
	InstrumentTypeID, 
	ApplyToIssuedRecord, 
	ApplyToDraftRecord,
	TemplateDocument, 
	DateCreated, 
	CreatedBySystemUserID,
	EnforceableUndertakingFlag,
	ApplicationAppliedFlag,
	ClockRequiredFlag,
	ClockID,
	LinkToAccountablePartyFlag,
	LinkToContactFlag,
	LinkToLocationFlag,
	ExternalNoticeFlag,
	IssuedByDelegatedOfficerFlag,
	DocumentRequiredFlag,
	PublicRegisterFlag,
	AppealableFlag,
	FeeApplicableFlag,
	FeeEditableFlag,
	ProgressFlag,
	FinalStageFlag,
	ProgressClockRequiredFlag, 
	ProgressClockID, 
	InpectionDateAppliedFlag, 
	FeeSentToSAPWhileIssueFlag, 
	ExemptionNoticeFlag,
	DateUpdated,
    UpdatedBySystemUserID
)
select 
	403, 
	538, 
	'Transporter Licence Variation',
	1,
	'TVAR',
	1 as LinkToPrimaryRecordFlag,
	1417,
	1 as ApplyToIssuedRecord,
	0 as ApplyToDraftRecord,
	TemplateDocument, 
	GETDATE(), 
	1 as ApplyToIssuedRecord,
	0 as EnforceableUndertakingFlag,
	0 as ApplicationAppliedFlag,
	1 as ClockRequiredFlag,
	14 as ClockID,
	0 as LinkToAccountablePartyFlag,
	0 as LinkToContactFlag,
	0 as LinkToLocationFlag,
	1 as ExternalNoticeFlag,
	1 as IssuedByDelegatedOfficerFlag,
	0 as DocumentRequiredFlag,
	1 as PublicRegisterFlag,
	0 as AppealableFlag,
	0 as FeeApplicableFlag,
	0 as FeeEditableFlag,
	0 as ProgressFlag,
	0 as FinalStageFlag,
	0 as ProgressClockRequiredFlag, 
	null as ProgressClockID, 
	0 as InpectionDateAppliedFlag, 
	0 as FeeSentToSAPWhileIssueFlag,
	0 as ExemptionNoticeFlag,
	getdate() as DateUpdated,
	1 as UpdatedBySystemUserID	 
	from tblNoticeTemplate
where NoticeTemplateID = 389

--- 404
insert into @tblNoticeTemplate
(
	NoticeTemplateID, 
	NoticeTemplateStatusID, 
	TemplateName, 
	SystemTemplateFlag, 
	SystemTemplateCode, 
	LinkToPrimaryRecordFlag, 
	InstrumentTypeID, 
	ApplyToIssuedRecord, 
	ApplyToDraftRecord,
	TemplateDocument, 
	DateCreated, 
	CreatedBySystemUserID,
	EnforceableUndertakingFlag,
	ApplicationAppliedFlag,
	ClockRequiredFlag,
	ClockID,
	LinkToAccountablePartyFlag,
	LinkToContactFlag,
	LinkToLocationFlag,
	ExternalNoticeFlag,
	IssuedByDelegatedOfficerFlag,
	DocumentRequiredFlag,
	PublicRegisterFlag,
	AppealableFlag,
	FeeApplicableFlag,
	FeeEditableFlag,
	ProgressFlag,
	FinalStageFlag,
	ProgressClockRequiredFlag, 
	ProgressClockID, 
	InpectionDateAppliedFlag, 
	FeeSentToSAPWhileIssueFlag, 
	ExemptionNoticeFlag,
DateUpdated,
UpdatedBySystemUserID
)
select 
	404, 
	538, 
	'Transporter Licence Suspension Notice',
	1,
	'TSPN',
	1 as LinkToPrimaryRecordFlag,
	1417,
	1 as ApplyToIssuedRecord,
	0 as ApplyToDraftRecord,
	TemplateDocument, 
	GETDATE(), 
	1 as CreatedBySystemUserID,
	0 as EnforceableUndertakingFlag,
	0 as ApplicationAppliedFlag,
	0 as ClockRequiredFlag,
	null as ClockID,
	0 as LinkToAccountablePartyFlag,
	0 as LinkToContactFlag,
	0 as LinkToLocationFlag,
	1 as ExternalNoticeFlag,
	1 as IssuedByDelegatedOfficerFlag,
	0 as DocumentRequiredFlag,
	1 as PublicRegisterFlag,
	0 as AppealableFlag,
	0 as FeeApplicableFlag,
	0 as FeeEditableFlag,
	0 as ProgressFlag,
	0 as FinalStageFlag,
	0 as ProgressClockRequiredFlag, 
	null as ProgressClockID, 
	0 as InpectionDateAppliedFlag, 
	0 as FeeSentToSAPWhileIssueFlag,
	0 as ExemptionNoticeFlag,
	getdate() as DateUpdated,
	1 as UpdatedBySystemUserID		 
	from tblNoticeTemplate
where NoticeTemplateID = 9

--- 405
insert into @tblNoticeTemplate
(
	NoticeTemplateID, 
	NoticeTemplateStatusID, 
	TemplateName, 
	SystemTemplateFlag, 
	SystemTemplateCode, 
	LinkToPrimaryRecordFlag, 
	InstrumentTypeID, 
	ApplyToIssuedRecord, 
	ApplyToDraftRecord,
	TemplateDocument, 
	DateCreated, 
	CreatedBySystemUserID,
	EnforceableUndertakingFlag,
	ApplicationAppliedFlag,
	ClockRequiredFlag,
	ClockID,
	LinkToAccountablePartyFlag,
	LinkToContactFlag,
	LinkToLocationFlag,
	ExternalNoticeFlag,
	IssuedByDelegatedOfficerFlag,
	DocumentRequiredFlag,
	PublicRegisterFlag,
	AppealableFlag,
	FeeApplicableFlag,
	FeeEditableFlag,
	ProgressFlag,
	FinalStageFlag,
	ProgressClockRequiredFlag, 
	ProgressClockID, 
	InpectionDateAppliedFlag, 
	FeeSentToSAPWhileIssueFlag, 
	ExemptionNoticeFlag,
	DateUpdated,
	UpdatedBySystemUserID
)
select 
	405, 
	538, 
	'Transporter Licence Revocation Notice',
	1,
	'TRVN',
	1 as LinkToPrimaryRecordFlag,
	1417,
	1 as ApplyToIssuedRecord,
	0 as ApplyToDraftRecord,
	TemplateDocument, 
	GETDATE(), 
	1 as CreatedBySystemUserID,
	0 as EnforceableUndertakingFlag,
	0 as ApplicationAppliedFlag,
	0 as ClockRequiredFlag,
	null as ClockID,
	0 as LinkToAccountablePartyFlag,
	0 as LinkToContactFlag,
	0 as LinkToLocationFlag,
	1 as ExternalNoticeFlag,
	1 as IssuedByDelegatedOfficerFlag,
	0 as DocumentRequiredFlag,
	1 as PublicRegisterFlag,
	0 as AppealableFlag,
	0 as FeeApplicableFlag,
	0 as FeeEditableFlag,
	0 as ProgressFlag,
	0 as FinalStageFlag,
	0 as ProgressClockRequiredFlag, 
	null as ProgressClockID, 
	0 as InpectionDateAppliedFlag, 
	0 as FeeSentToSAPWhileIssueFlag,
	0 as ExemptionNoticeFlag,
	getdate() as DateUpdated,
	1 as UpdatedBySystemUserID		 
	from tblNoticeTemplate
where NoticeTemplateID = 8

--- 406
insert into @tblNoticeTemplate
(
	NoticeTemplateID, 
	NoticeTemplateStatusID, 
	TemplateName, 
	SystemTemplateFlag, 
	SystemTemplateCode, 
	LinkToPrimaryRecordFlag, 
	InstrumentTypeID, 
	ApplyToIssuedRecord, 
	ApplyToDraftRecord,
	TemplateDocument, 
	DateCreated, 
	CreatedBySystemUserID,
	EnforceableUndertakingFlag,
	ApplicationAppliedFlag,
	ClockRequiredFlag,
	ClockID,
	LinkToAccountablePartyFlag,
	LinkToContactFlag,
	LinkToLocationFlag,
	ExternalNoticeFlag,
	IssuedByDelegatedOfficerFlag,
	DocumentRequiredFlag,
	PublicRegisterFlag,
	AppealableFlag,
	FeeApplicableFlag,
	FeeEditableFlag,
	ProgressFlag,
	FinalStageFlag,
	ProgressClockRequiredFlag, 
	ProgressClockID, 
	InpectionDateAppliedFlag, 
	FeeSentToSAPWhileIssueFlag, 
	ExemptionNoticeFlag,
	DateUpdated,
	UpdatedBySystemUserID
)
select 
	406, 
	538, 
	'Transporter Licence Approval of the Surrender of a Licence',
	1,
	'TSUR',
	1 as LinkToPrimaryRecordFlag,
	1417,
	1 as ApplyToIssuedRecord,
	0 as ApplyToDraftRecord,
	TemplateDocument, 
	GETDATE(), 
	1 as CreatedBySystemUserID,
	0 as EnforceableUndertakingFlag,
	0 as ApplicationAppliedFlag,
	0 as ClockRequiredFlag,
	null as ClockID,
	0 as LinkToAccountablePartyFlag,
	0 as LinkToContactFlag,
	0 as LinkToLocationFlag,
	1 as ExternalNoticeFlag,
	1 as IssuedByDelegatedOfficerFlag,
	0 as DocumentRequiredFlag,
	1 as PublicRegisterFlag,
	0 as AppealableFlag,
	0 as FeeApplicableFlag,
	0 as FeeEditableFlag,
	0 as ProgressFlag,
	0 as FinalStageFlag,
	0 as ProgressClockRequiredFlag, 
	null as ProgressClockID, 
	0 as InpectionDateAppliedFlag, 
	0 as FeeSentToSAPWhileIssueFlag,
	0 as ExemptionNoticeFlag,
	getdate() as DateUpdated,
	1 as UpdatedBySystemUserID		 
	from tblNoticeTemplate
where NoticeTemplateID = 391

--407
insert into @tblNoticeTemplate
(
	NoticeTemplateID, 
	NoticeTemplateStatusID, 
	TemplateName, 
	SystemTemplateFlag, 
	SystemTemplateCode, 
	LinkToPrimaryRecordFlag, 
	InstrumentTypeID, 
	ApplyToIssuedRecord, 
	ApplyToDraftRecord,
	TemplateDocument, 
	DateCreated, 
	CreatedBySystemUserID,
	EnforceableUndertakingFlag,
	ApplicationAppliedFlag,
	ClockRequiredFlag,
	ClockID,
	LinkToAccountablePartyFlag,
	LinkToContactFlag,
	LinkToLocationFlag,
	ExternalNoticeFlag,
	IssuedByDelegatedOfficerFlag,
	DocumentRequiredFlag,
	PublicRegisterFlag,
	AppealableFlag,
	FeeApplicableFlag,
	FeeEditableFlag,
	ProgressFlag,
	FinalStageFlag,
	ProgressClockRequiredFlag, 
	ProgressClockID, 
	InpectionDateAppliedFlag, 
	FeeSentToSAPWhileIssueFlag, 
	ExemptionNoticeFlag,
	DateUpdated,
	UpdatedBySystemUserID
)
select 
	407, 
	538, 
	'Transporter Licence Transfer',
	1 as SystemTemplateFlag,
	'TTRF',
	1 as LinkToPrimaryRecordFlag,
	1417,
	1 as ApplyToIssuedRecord,
	0 as ApplyToDraftRecord,
	TemplateDocument, 
	GETDATE(), 
	1 as CreatedBySystemUserID,
	0 as EnforceableUndertakingFlag,
	1 as ApplicationAppliedFlag,
	0 as ClockRequiredFlag,
	null as ClockID,
	1 as LinkToAccountablePartyFlag,
	1 as LinkToContactFlag,
	0 as LinkToLocationFlag,
	1 as ExternalNoticeFlag,
	0 as IssuedByDelegatedOfficerFlag,
	0 as DocumentRequiredFlag,
	1 as PublicRegisterFlag,
	0 as AppealableFlag,
	0 as FeeApplicableFlag,
	0 as FeeEditableFlag,
	0 as ProgressFlag,
	0 as FinalStageFlag,
	0 as ProgressClockRequiredFlag, 
	null as ProgressClockID, 
	0 as InpectionDateAppliedFlag, 
	0 as FeeSentToSAPWhileIssueFlag,
	0 as ExemptionNoticeFlag,
	getdate() as DateUpdated,
	1 as UpdatedBySystemUserID		 
	from tblNoticeTemplate
where NoticeTemplateID = 379
select * from @tblNoticeTemplate
 

