ALTER DATABASE [CUSSReportingDB_HGH] SET EMERGENCY;
GO
ALTER DATABASE [CUSSReportingDB_HGH] set single_user
GO
DBCC CHECKDB ([CUSSReportingDB_HGH], REPAIR_ALLOW_DATA_LOSS) WITH ALL_ERRORMSGS;
GO
ALTER DATABASE [CUSSReportingDB_HGH] set multi_user
GO