--Even though [ID] is identity key in table: FaultType
--we still can provide values and insert into it

SET IDENTITY_INSERT [dbo].[FaultType] ON 

INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (1, 66, N'BagWithStraps', N'BagWithStraps')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (2, 110, N'ConveyorHasFaultedWhileMovingBag', N'ConveyorHasFaultedWhileMovingBag')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (3, 86, N'MultiBagScan', N'MultiBagScan')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (4, 109, N'BagTakingTooLongToGetReleased', N'BagTakingTooLongToGetReleased')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (5, 75, N'BaggageReferenceNotExists', N'BaggageReferenceNotExists')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (6, 6, N'BagNotInactiveOnFirstLeg', N'BagNotInactiveOnFirstLeg')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (7, 58, N'OverMaxNumberOfOversizeRescan', N'OverMaxNumberOfOversizeRescan')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (8, 0, N'None', N'None')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (9, 102, N'ExcessBagDetected', N'ExcessBagDetected')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (10, 89, N'FlightIsNotOnSubsequentLegFlightRangeTable', N'FlightIsNotOnSubsequentLegFlightRangeTable')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (11, 103, N'BioRejectUSPassenger', N'BioRejectUSPassenger')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (12, 71, N'OperatingCarrierNotSupported', N'OperatingCarrierNotSupported')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (13, 24, N'FailedToUpdateBag', N'FailedToUpdateBag')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (14, 69, N'MultipleBagTagsDetected', N'MultipleBagTagsDetected')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (15, 39, N'IncorrectPortForBoardpass', N'IncorrectPortForBoardpass')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (16, 55, N'FailedIDCust', N'FailedIDCust')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (17, 37, N'HighPriorityCommentsFound', N'HighPriorityCommentsFound')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (18, 62, N'OverMaxNumberOf3DReScan', N'OverMaxNumberOf3DReScan')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (19, 50, N'RejectableSSRDetected', N'RejectableSSRDetected')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (20, 49, N'OverMaxNumberOfMultiBagTagReads', N'OverMaxNumberOfMultiBagTagReads')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (21, 48, N'OverMaxNumberOfMismatch', N'OverMaxNumberOfMismatch')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (22, 54, N'WeightChanged', N'WeightChanged')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (23, 21, N'DidNotRemoveOldHeavyTag', N'DidNotRemoveOldHeavyTag')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (24, 23, N'FailedToRetrieveExcessInfo', N'FailedToRetrieveExcessInfo')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (25, 22, N'ExcessIsNull', N'ExcessIsNull')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (26, 46, N'OverMaxNumberOfFailedBagTagReads', N'OverMaxNumberOfFailedBagTagReads')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (27, 47, N'OverMaxNumberOfFailedHeavyTagReads', N'OverMaxNumberOfFailedHeavyTagReads')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (28, 11, N'CustFailedValidation', N'CustFailedValidation')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (29, 26, N'FlightAtGate', N'FlightAtGate')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (30, 64, N'BagOversizedBy3D', N'BagOversizedBy3D')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (31, 28, N'FlightClosed', N'FlightClosed')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (32, 67, N'BagTagNotTheSame', N'BagTagNotTheSame')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (33, 60, N'UpdateBagAborted', N'UpdateBagAborted')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (34, 53, N'UnableToParseBagDetail', N'UnableToParseBagDetail')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (35, 45, N'NotAllLegsOpenForAcceptance', N'NotAllLegsOpenForAcceptance')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (36, 16, N'CustNotAcceptedInAllLegs', N'CustNotAcceptedInAllLegs')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (37, 15, N'CustNotAcceptedFirstLeg', N'CustNotAcceptedFirstLeg')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (38, 35, N'FlightSuspended', N'FlightSuspended')
INSERT [dbo].[FaultType] ([ID], [Code], [ShortName], [Description]) VALUES (39, 30, N'FlightFinalised', N'FlightFinalised')
SET IDENTITY_INSERT [dbo].[FaultType] OFF
