
SELECT [ROW_ID]
      ,[TRAVLR_UCI]
      ,[PNR_REF]
      ,[FLIGHT_NO]
      ,[LOCLDEPD]
      ,[DEPUPOR]
      ,[BAG_UBI_ID]
      ,[HIST_TRANS_ID]
      ,[BAG_TAG]
      ,[Q_BAG_TAG_ID]
      ,[OFFICE_ID]
      ,[USER_SONIC_ID]
      ,[HIST_CATG_CODE]
      ,[HIST_SUB_CAT_CODE]
      ,[SERVICE_REF]
      ,[BAG_WGT]
      ,[BAG_WGT_UOM]
      ,[TRANS_SEQ_NO]
      ,[ACTIVITY_TSMP]
      ,[ACTIVITY_TSMP_UT+10]
      ,[F20]
  FROM [CUSSReportingDB].[dbo].[QantasMay2021DataSheet]
  WHERE not [PNR_REF] is null and datePart(year, [ACTIVITY_TSMP_UT+10]) = 2021 and datePart(month, [ACTIVITY_TSMP_UT+10]) = 5  --departure date time: 5508  [ACTIVITY_TSMP] as calculation: 5471  [ACTIVITY_TSMP_UT+10] as calculation: 5513


  SELECT [ROW_ID]
      ,[TRAVLR_UCI]
      ,[PNR_REF]
      ,[FLIGHT_NO]
      ,[LOCLDEPD]
      ,[DEPUPOR]
      ,[BAG_UBI_ID]
      ,[HIST_TRANS_ID]
      ,[BAG_TAG]
      ,[Q_BAG_TAG_ID]
      ,[OFFICE_ID]
      ,[USER_SONIC_ID]
      ,[HIST_CATG_CODE]
      ,[HIST_SUB_CAT_CODE]
      ,[SERVICE_REF]
      ,[BAG_WGT]
      ,[BAG_WGT_UOM]
      ,[TRANS_SEQ_NO]
      ,[ACTIVITY_TSMP]
      ,[ACTIVITY_TSMP_UT+10]
      ,[F20]
  FROM [CUSSReportingDB].[dbo].[QantasMay2021DataSheet]
  WHERE not [PNR_REF] is null and NOT(datePart(year, [ACTIVITY_TSMP_UT+10]) = 2021 and datePart(month, [ACTIVITY_TSMP_UT+10]) = 5)  --departure date time: 335 [ACTIVITY_TSMP] as calculation: 377 [ACTIVITY_TSMP_UT+10] as calculation: 355