	SELECT [EMAssessmentCategoryID]
		  ,[EMAssessmentCategory]
		  ,[EMAssessmentSectionID]
		  ,[EMAssessmentSection]
		  ,A.[EMAssessmentQuestionID]
		  ,[EMAssessmentQuestion]
		  ,A.[EMAssessmentAnswerID]
		  ,A.[EMAssessmentAnswer]
		  ,A.[Score]
		  ,A.[AutoGeneratedFlag]
		  ,B.ScoreFactor
		  ,A.ToolTip
	FROM [viewEMAssessmentQuestionAnswer] A INNER JOIN tblEMAssessmentAnswer B
	ON A.EMAssessmentAnswerID = B.EMAssessmentAnswerID