--check a constraint of a table:
SELECT * 
FROM sys.foreign_keys
WHERE referenced_object_id = object_id('BagScanTransaction')

--you will get a line of constraint => FK_REF_BagScanTransaction_BagStates3D_BagScanTransaction

if exists(SELECT * 
FROM sys.foreign_keys
WHERE referenced_object_id = object_id('BagScanTransaction'))
begin
	SELECT 
		'ALTER TABLE [' +  OBJECT_SCHEMA_NAME(parent_object_id) +
		'].[' + OBJECT_NAME(parent_object_id) + 
		'] DROP CONSTRAINT [' + name + ']'
	FROM sys.foreign_keys
	WHERE referenced_object_id = object_id('BagScanTransaction')
end

--script generated by above command lines ===> ALTER TABLE [dbo].[REF_BagScanTransaction_BagStates3D] DROP CONSTRAINT [FK_REF_BagScanTransaction_BagStates3D_BagScanTransaction]