

 
SELECT ISNULL([TRAVEL_ROUTES], '') as ROUTE_VALUE, 
LEN(ISNULL([TRAVEL_ROUTES], '')) as LEN_VALUE,
(CASE LEN(ISNULL([TRAVEL_ROUTES], '')) 
  WHEN 0 THEN ISNULL([TRAVEL_ROUTES], '')
  WHEN 1 THEN SUBSTRING(ISNULL([TRAVEL_ROUTES], ''), 1, 1)
  WHEN 2 THEN SUBSTRING(ISNULL([TRAVEL_ROUTES], ''), 1, 1) 
  + (case IsNumeric(SUBSTRING(ISNULL([TRAVEL_ROUTES], ''), 2, 1)) when 1 then SUBSTRING(ISNULL([TRAVEL_ROUTES], ''), 2, 1) else '' end)
  WHEN 3 THEN SUBSTRING(ISNULL([TRAVEL_ROUTES], ''), 1, 1) 
  + (case IsNumeric(SUBSTRING(ISNULL([TRAVEL_ROUTES], ''), 2, 1)) when 1 then SUBSTRING(ISNULL([TRAVEL_ROUTES], ''), 2, 1) else '' end)
  + (case IsNumeric(SUBSTRING(ISNULL([TRAVEL_ROUTES], ''), 3, 1)) when 1 then SUBSTRING(ISNULL([TRAVEL_ROUTES], ''), 3, 1) else '' end)
 END) AS FINAL_VALUE
FROM [PALMSDocDB].[dbo].[ToBeDeletedTemp]


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ToBeDeletedTemp](
	[STU_ID] [int] NULL,
	[GIVEN_NAME] [nvarchar](50) NULL,
	[FAMILY_NAME] [nvarchar](50) NULL,
	[SUBURB] [varchar](50) NULL,
	[POSTCODE] [varchar](10) NULL,
	[TRAVEL_ROUTES] [nvarchar](50) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO