declare @STU_INFO_TEMP table 
( 
  STU_ID INT,
  GIVEN_NAME varchar(50),
  FAMILY_NAME varchar(50),
  SUBURB varchar(50),
  POSTCODE varchar(10), 
  TRAVEL_ROUTES_ID INT,
  ASSIGN_CLASS_ID INT NULL 
)
 
INSERT INTO @STU_INFO_TEMP(STU_ID, GIVEN_NAME, FAMILY_NAME, SUBURB, POSTCODE, TRAVEL_ROUTES_ID, ASSIGN_CLASS_ID) VALUES (1, 'JimA', 'Smith', 'Burwood', '2207', 3, null)
INSERT INTO @STU_INFO_TEMP(STU_ID, GIVEN_NAME, FAMILY_NAME, SUBURB, POSTCODE, TRAVEL_ROUTES_ID, ASSIGN_CLASS_ID) VALUES (2, 'JimB', 'Smith', 'Burwood', '2207', 3, null)
INSERT INTO @STU_INFO_TEMP(STU_ID, GIVEN_NAME, FAMILY_NAME, SUBURB, POSTCODE, TRAVEL_ROUTES_ID, ASSIGN_CLASS_ID) VALUES (3, 'JimC', 'Smith', 'Burwood', '2207', 8, null)
INSERT INTO @STU_INFO_TEMP(STU_ID, GIVEN_NAME, FAMILY_NAME, SUBURB, POSTCODE, TRAVEL_ROUTES_ID, ASSIGN_CLASS_ID) VALUES (4, 'JimD', 'Smith', 'Burwood', '2207', 3, null)
INSERT INTO @STU_INFO_TEMP(STU_ID, GIVEN_NAME, FAMILY_NAME, SUBURB, POSTCODE, TRAVEL_ROUTES_ID, ASSIGN_CLASS_ID) VALUES (5, 'JimE', 'Smith', 'Burwood', '2207', 2, null)
INSERT INTO @STU_INFO_TEMP(STU_ID, GIVEN_NAME, FAMILY_NAME, SUBURB, POSTCODE, TRAVEL_ROUTES_ID, ASSIGN_CLASS_ID) VALUES (6, 'JimF', 'Smith', 'Burwood', '2207', 9, null)
INSERT INTO @STU_INFO_TEMP(STU_ID, GIVEN_NAME, FAMILY_NAME, SUBURB, POSTCODE, TRAVEL_ROUTES_ID, ASSIGN_CLASS_ID) VALUES (7, 'JimG', 'Smith', 'Burwood', '2207', 3, null)
INSERT INTO @STU_INFO_TEMP(STU_ID, GIVEN_NAME, FAMILY_NAME, SUBURB, POSTCODE, TRAVEL_ROUTES_ID, ASSIGN_CLASS_ID) VALUES (8, 'JimH', 'Smith', 'Burwood', '2207', 1, null)

SELECT * FROM @STU_INFO_TEMP
-----------------------------------------
declare @tblLookup table 
( 
  ROW_ID INT, 
  VAL INT
)
INSERT INTO @tblLookup (ROW_ID, VAL) VALUES(1, 30)
-----------------------------------------
declare @RoutesStudents table 
( 
  ROW_ID INT,
  ROUTES_ID INT,
  STU_COUNT INT
)
INSERT INTO @RoutesStudents (ROW_ID, ROUTES_ID, STU_COUNT) VALUES(1, 3, 27)
INSERT INTO @RoutesStudents (ROW_ID, ROUTES_ID, STU_COUNT) VALUES(2, 8, 35)
INSERT INTO @RoutesStudents (ROW_ID, ROUTES_ID, STU_COUNT) VALUES(3, 6, 18)
INSERT INTO @RoutesStudents (ROW_ID, ROUTES_ID, STU_COUNT) VALUES(4, 2, 16)
 
--Get first row
SELECT TOP 1 A.* FROM @RoutesStudents AS A
WHERE A.ROW_ID IN (
SELECT TOP 1 ROW_ID
FROM @RoutesStudents
order by ROW_ID
)
ORDER BY A.ROW_ID DESC 



--Get second row
SELECT TOP 1 A.* FROM @RoutesStudents AS A
WHERE A.ROW_ID IN (
SELECT TOP 2 ROW_ID
FROM @RoutesStudents
order by ROW_ID
)
ORDER BY A.ROW_ID DESC 
--Get third row
SELECT TOP 1 A.* FROM @RoutesStudents AS A
WHERE A.ROW_ID IN (
SELECT TOP 3 ROW_ID
FROM @RoutesStudents
order by ROW_ID
)
ORDER BY A.ROW_ID DESC 
--Get fourth row
SELECT TOP 1 A.* FROM @RoutesStudents AS A
WHERE A.ROW_ID IN (
SELECT TOP 4 ROW_ID
FROM @RoutesStudents
order by ROW_ID
)
ORDER BY A.ROW_ID DESC 
 
----------------------------------------
declare @SixClass table 
( 
  CLASS_ID INT,
  CLASS_NAME varchar(20)
)
INSERT INTO @SixClass (CLASS_ID, CLASS_NAME) VALUES(1, '7A')
INSERT INTO @SixClass (CLASS_ID, CLASS_NAME) VALUES(2, '7B')
INSERT INTO @SixClass (CLASS_ID, CLASS_NAME) VALUES(3, '7C')
INSERT INTO @SixClass (CLASS_ID, CLASS_NAME) VALUES(4, '7D')
INSERT INTO @SixClass (CLASS_ID, CLASS_NAME) VALUES(5, '7E')
INSERT INTO @SixClass (CLASS_ID, CLASS_NAME) VALUES(6, '7F')

SELECT * FROM @SixClass