 
        declare @InstrumentID int
        SELECT @InstrumentID = 4000004
        
        declare @PrimaryInstrumentID int
        select @PrimaryInstrumentID = POEOLicenceIntrumentID from tblRiskAssessment where InstrumentID = @InstrumentID
        
     	SET NOCOUNT ON;	
 
		---------- Create EMA category, section, answer --------------------------------
		Declare @tblData2 Table 
			(
				SNo int IDENTITY(1,1), 
				EMAssessmentCategoryID INT,		
				EMAssessmentSectionID INT,
				EMAssessmentQuestionID INT	,
				EMAssessmentAnswerID INT,
				Score INT,
				AutoGeneratedFlag BIT				
			)	
					
		INSERT INTO @tblData2
			EXEC DBO.uspEMAGetAnswer @PrimaryInstrumentID, @InstrumentID
		
		------------------------------------------------------
		Declare @tblData1 Table 
				(
					SNo int IDENTITY(1,1), 
					EMAssessmentSectionID INT					
				)		
		
		---get all category list
		Declare @tblData Table 
			(
				SNo int IDENTITY(1,1), 
				EMAssessmentCategoryID INT					
			)		
		INSERT INTO @tblData(EMAssessmentCategoryID)
		SELECT EMAssessmentCategoryID FROM tblEMAssessmentCategory
		
		 	
 	    DECLARE @Cnt1 INT
 	    DECLARE @EMAssessmentCategoryID INT
 	    DECLARE @EMAssessmentResultCategory INT
 	    
 	    SELECT @Cnt1 = 1
		
		WHILE (1=1)
		BEGIN
				--get all category list total 
				SELECT @EMAssessmentCategoryID = EMAssessmentCategoryID 
				FROM @tblData WHERE SNo = @Cnt1
				
				--print '@EMAssessmentSectionID TOP =' + cast(@EMAssessmentCategoryID as varchar)
				
				IF @@ROWCOUNT = 0
				BREAK
				
				DELETE FROM @tblData1
				
				IF NOT EXISTS(SELECT EMAssessmentResultCategoryID FROM tblEMAssessmentResultCategory WHERE InstrumentID = @InstrumentID)
				BEGIN
					INSERT INTO tblEMAssessmentResultCategory
 						(InstrumentID,
 						 EMAssessmentCategoryID,
 						 DateCreated,
 						 CreatedBySystemUserID)
 					SELECT 	@InstrumentID, @EMAssessmentCategoryID, GETDATE(), 1			
					SELECT @EMAssessmentResultCategory = @@IDENTITY
					
					--insert all sectionIDs into table @tblData1 under current categoryID
					INSERT INTO @tblData1(EMAssessmentSectionID)
					SELECT EMAssessmentSectionID 
					FROM tblEMAssessmentSection 
					WHERE EMAssessmentCategoryID = @EMAssessmentCategoryID					
				END
				ELSE
				BEGIN				    
					INSERT INTO @tblData1(EMAssessmentSectionID)
					SELECT EMAssessmentSectionID 
					FROM tblEMAssessmentResultSection A INNER JOIN tblEMAssessmentResultCategory C 
                                  ON A.EMAssessmentResultCategoryID = C.EMAssessmentResultCategoryID  
					              WHERE C.InstrumentID = @InstrumentID and C.EMAssessmentCategoryID = @EMAssessmentCategoryID		
					
					SELECT @EMAssessmentResultCategory = A.EMAssessmentResultCategoryID FROM tblEMAssessmentResultSection A INNER JOIN tblEMAssessmentResultCategory C 
                                  ON A.EMAssessmentResultCategoryID = C.EMAssessmentResultCategoryID  
					              WHERE C.InstrumentID = @InstrumentID and C.EMAssessmentCategoryID = @EMAssessmentCategoryID			 				   
				END	
				
				select * from @tblData1
				
				DECLARE @Cnt8 INT
				DECLARE @EMAssessmentSectionID INT = 0
				DECLARE @EMAssessmentResultSectionID INT = 0
				
				SELECT @Cnt8 = MIN(SNo) FROM @tblData1				
				declare @test int
				select @test = count(*)  from @tblData1
				
				--print cast(@test as varchar(10))
					
				WHILE (1=1)
				BEGIN
					SELECT @EMAssessmentSectionID = EMAssessmentSectionID 
					FROM @tblData1 WHERE SNo = @Cnt8
					
					IF @@ROWCOUNT = 0
					BREAK
					
					IF NOT EXISTS(SELECT * FROM tblEMAssessmentResultSection A INNER JOIN tblEMAssessmentResultCategory C 
                                  ON A.EMAssessmentResultCategoryID = C.EMAssessmentResultCategoryID  
					              WHERE C.InstrumentID = @InstrumentID 
					              and A.EMAssessmentResultCategoryID = @EMAssessmentResultCategory 
					              and A.EMAssessmentSectionID = @EMAssessmentSectionID)
					BEGIN
						--INSERT INTO tblEMAssessmentResultSection
						--	(EMAssessmentResultCategoryID,EMAssessmentSectionID,DateCreated,CreatedBySystemUserID)
						--SELECT 	@EMAssessmentResultCategory, @EMAssessmentSectionID, GETDATE(),1		
									
						--SELECT @EMAssessmentResultSectionID = @@IDENTITY						
						print 'no exist tblEMAssessmentResultSection'
						print '@EMAssessmentResultCategory=' + cast(@EMAssessmentResultCategory as varchar)
						print '@EMAssessmentSectionID=' + cast(@EMAssessmentSectionID as varchar)
						print ''
					END
					
					IF NOT EXISTS(SELECT A.EMAssessmentResultSectionID FROM tblEMAssessmentResultAnswer A
					INNER JOIN tblEMAssessmentResultSection B
					  ON A.EMAssessmentResultSectionID = B.EMAssessmentResultSectionID
					  INNER JOIN tblEMAssessmentResultCategory C 
					  ON B.EMAssessmentResultCategoryID = C.EMAssessmentResultCategoryID 
					WHERE C.InstrumentID = @InstrumentID and A.EMAssessmentResultSectionID =@EMAssessmentResultSectionID and EMAssessmentAnswerID IN 
					   (SELECT EMAssessmentAnswerID
						FROM tblEMAssessmentAnswer 
						WHERE EMAssessmentQuestionID IN
						(SELECT EMAssessmentQuestionID FROM tblEMAssessmentQuestion 
							WHERE EMAssessmentSectionID = @EMAssessmentSectionID AND QuestionTypeID IN (683,684))))
					BEGIN
						--INSERT INTO tblEMAssessmentResultAnswer(EMAssessmentResultSectionID, EMAssessmentAnswerID, DateCreated, CreatedBySystemUserID)
						SELECT 	@EMAssessmentResultSectionID, EMAssessmentAnswerID, GETDATE(), 1
						FROM tblEMAssessmentAnswer WHERE EMAssessmentQuestionID IN
						(SELECT EMAssessmentQuestionID FROM tblEMAssessmentQuestion 
							WHERE EMAssessmentSectionID = @EMAssessmentSectionID AND QuestionTypeID IN (683,684))
						
						print 'insert into tblEMAssessmentResultAnswer'
					END
					
					--@tblData2 contains all defalut answer data, we only update it when it is null value
					UPDATE tblEMAssessmentResultAnswer
					SET EnteredValue = B.Score
					FROM tblEMAssessmentResultAnswer A, @tblData2 B
					WHERE A.EMAssessmentAnswerID = B.EMAssessmentAnswerID AND
							A.EMAssessmentResultSectionID = @EMAssessmentResultSectionID AND
							B.AutoGeneratedFlag = 1 and EnteredValue IS NULL
					 						
					SELECT @Cnt8 = @Cnt8 +1
				END
			
			SELECT @Cnt1 = @Cnt1 +1
		END 
  
  	    delete @tblData
  	    delete @tblData1
  	    delete @tblData2
  
  
