SELECT    
y.EMAssessmentCategoryID, 
y.EMAssessmentCategory, 
a.EMAssessmentSectionID, 
a.EMAssessmentSection, 
b.EMAssessmentQuestionID, 
b.EMAssessmentQuestion, 
c.EMAssessmentAnswerID, 
c.EMAssessmentAnswer, 
c.Score, 
c.AutoGeneratedFlag, 
b.ToolTip

FROM         

dbo.tblEMAssessmentCategory AS y INNER JOIN
dbo.tblEMAssessmentSection AS a ON y.EMAssessmentCategoryID = a.EMAssessmentCategoryID INNER JOIN
dbo.tblEMAssessmentQuestion AS b ON a.EMAssessmentSectionID = b.EMAssessmentSectionID INNER JOIN
dbo.tblEMAssessmentAnswer AS c ON b.EMAssessmentQuestionID = c.EMAssessmentQuestionID INNER JOIN 
tblEMAssessmentAnswer X ON C.EMAssessmentAnswerID = X.EMAssessmentAnswerID

ORDER BY y.EMAssessmentCategoryID, a.EMAssessmentSectionID, b.SequenceOrder, c.SequenceNumber