USE [DepositPower]
GO 

--CREATE INDEX IX_AU_PAYMENT_POLICY_CODE ON AU_PAYMENT(POLICY_CODE);

--AU_APPLICANT

--CREATE INDEX IX_AU_APPLICANT_POLICY_CODE ON AU_APPLICANT(POLICY_CODE);
--CREATE INDEX IX_AU_PROPERTY_POLICY_CODE ON AU_PROPERTY(POLICY_CODE);